client/squawkers.js
client/tiny.js
scripts/setup-and-run-janus.sh

Makes it easier to setup a local janus server that mr-social-client can use without insecure connection errors.
Also important for Google Chrome support since Chrome doesn't allow getUserMedia from non-secure pages.

Setup script now runs a secure server + associated client changes

---

client/squawkers.js
client/tiny.js
docs/api.md
src/lib.rs
src/messages.rs

Now room IDs and user IDs are arbitrary strings. Would be nice to fix unnecessary copying but this implementation should be OK for now.
For the moment, we continue to accept numeric JSON IDs in signalling messages; later, once client code is updated, we'll break backwards compatibility. This change does make the user IDs returned in signalling responses into strings, which could break client code, but ours is resilient to that (and since IDs are opaque and only good for comparing equality probably other code is also resilient to that.)

Store, accept string room and user IDs

---

Cargo.lock
docs/api.md
src/lib.rs
src/messages.rs
src/sessions.rs
src/switchboard.rs

This is still rough, but should be sufficient to get started on client-side work. To wit:
- You can now send "block" and "unblock" signalling messages to the server, specifying a user ID you wish to block or unblock.
- These manipulate the state of an in-memory database of blocks, and send an event to the target user that they have been blocked or unblocked.
- When forwarding packets, we respect these blocks. No audio, video, or data will be sent from blockers to their blockees, or from blockees to their blockers.
There is a known issue with video transmission, where when a blocked video stream is unblocked Janus will interpret the gap as packet loss and start sending a ton of NACKs. I'm researching the best approach to this. It could be that we will want to advise clients to unsubscribe …

Implement user-to-user blocking

---

docs/api.md
src/lib.rs
src/messages.rs

We don't have a use case for this in the current product, and we don't want to allow it anyway unless we have a use case since we want rooms to be private unless their ID is shared.

Don't allow clients to see rooms they aren't in

---

Cargo.lock
Cargo.toml
src/lib.rs
src/sessions.rs
src/switchboard.rs

Clean up switchboard interface to return slices instead of vectors, do less per-packet work cloning `Arc`s, other small efficiencies.

Switchboard improving

---

src/config.rs
src/lib.rs
src/switchboard.rs

This is a nice failsafe to have around in case we have some kind of load-related problem after launch.
Also, `max_room_size` is now an inclusive instead of exclusive upper bound, which seems to make more sense.

Implement configurable maximum server-wide CCU

---

Cargo.toml
scripts/setup-and-run-janus.sh

Enabling LTO cuts the binary size in half, go figure. Maybe it makes it faster too.

Adjustment to build-related stuff

---

src/messages.rs

Ever since https://github.com/mozilla/naf-janus-adapter/pull/37 was deployed, all of our clients are sending us string IDs, so we can drop support for numeric IDs.

Only support string room and user IDs

---

src/lib.rs
src/messages.rs
src/switchboard.rs
src/txid.rs

This is mostly aimed at making logging output much more useful and readable, by waiting until things are dereferenced/parsed to log them. To accomplish that sanely a reasonable amount of refactoring in the signalling message parsing was necessary.
Also snuck in the use of new `impl Trait` stuff to make switchboard interface not allocate per-packet.

Miscellaneous fixes

---

Cargo.lock
Cargo.toml
src/lib.rs

This is important for Hubs, and I think it should be good for basically anyone who wants to ever use this plugin, although this SDP negotiation is getting very fiddly so a refactoring to make it more flexible/configurable is probably in order someday.

Negotiate mono and DTX with clients

---

client/tiny.js
docs/api.md
src/lib.rs
src/messages.rs

This is immediately useful to us because SCTP is the cause of some bugginess and we need end-to-end reliability, but it's easy to see how it could be generally useful for anyone.

Support sending arbitrary data over signalling transport

---

scripts/setup-and-run-janus.sh
src/auth.rs
src/lib.rs
src/switchboard.rs

- Just extract join and kick claims from JWT, instead of trying to parse subject.
- Actually act on kick message by verifying claim and calling `end_session` on given publisher

Authorize and kick

---

src/lib.rs

This version seems more readable to me. Also, fixed log messages to not warn in the common case of allowed joins.

Clean up join authorization logic

---

Cargo.lock
Cargo.toml
src/lib.rs

What it says on the tin. Trivial upgrade, but backwards-incompatible with older versions.

Upgrade to accommodate Janus 0.7.6

---

src/lib.rs
src/switchboard.rs

Refactors `get_publisher` to use a new hashmap to reduce the need to walk all sessions when fetching publishers. Instead, we now only walk the sessions in the first room the user joined. `get_sessions` could also be refactored but proved challenging for me.
Also it seems that `get_publisher` assumes a user is only publishing in one room (ie, has one subscriber offer across all of their joined rooms), but `get_sessions` assumes a user can be joined in several rooms. So this PR may be a bad idea, since the new hashmap now assumes a user is going to publish from the first room they join. I wasn't sure of the original assumptions being made in switchboard - in practice users only join one room in hubs for both publishing and subscribing. This PR assumes that the first room a user joins is the …

Attempt faster lookup of publishers

---

src/lib.rs
src/sessions.rs
src/switchboard.rs

**WIP -- haven't tested yet. Just putting it here in case it's useful to you.**
This fixes #52 and changes the switchboard data structures to be more sympathetic to how we're using them. We can now do `get_publisher` in constant time and kicking users also got faster. Hopefully the code also got cleaner and harder to mess up.
To do still:

Refactor & fix switchboard join/leave tracking

---

Cargo.lock
Cargo.toml
src/lib.rs

See discussion on https://github.com/mozilla/janus-plugin-sfu/issues/58
I started from @feymartynov work and made additional changes in janus-plugin-rs https://github.com/netology-group/janus-plugin-rs/pull/1
The code compile but not currently fully working, I still have an issue generating the sdp offer based on the sdp answer where ` answer.get_payload_type(VIDEO_CODEC.to_cstr())` is returning None.

Update to latest janus 0.10.x (api v15)

---

src/switchboard.rs

Doesn't change anything because UserId and RoomId are both string, but it's better to have the right type.

Fix room param type

---

src/lib.rs

This shows:
```
Loaded SFU plugin configuration: Config { auth_key: None, max_room_size: 30, max_ccu: 1000, message_threads: 0 }
message_threads is set to 0, setting it to 8 (number of cpus)
```

Log how many message threads will be created

---

src/lib.rs

See my comment https://github.com/mozilla/janus-plugin-sfu/issues/62#issuecomment-770406570
We don't seem to change anything in process_data, using `read()` instead of `write()` is better to not block concurrent execution with message_threads > 1.
Or is there something I'm missing?

Use SWITCHBOARD.read() instead of SWITCHBOARD.write() in process_data

---

src/lib.rs

I think when I first wrote this I misunderstood how `const` works in Rust. `const` makes the compiler just do a compile-time substitution of the value into each of its references, so it was making a new temporary `Plugin` object every time it needed to create a plugin handle pointer to pass into Janus. `static` is what we actually want.

Make PLUGIN static instead of const

---

Cargo.lock
Cargo.toml
src/switchboard.rs

This wasn't really pulling its weight, and killing it decreases the surface area for bugs like #62.
Also now we don't leak an empty vec in maps for every user and room that ever exists which is nice.

Remove multimap dependency

---

src/lib.rs

Using log level info (level 4) and using websocket for naf components update, you can really have a lot of logs, several times per second for an user. Lower it to verb (level 5)

Use level verb instead of info for the 'Queueing signalling message' log

---

src/lib.rs
src/switchboard.rs

Fixes #57. (It was also off by one.)

Make max_ccu based on users, not sessions

---

README.md

Now that I'm the new maintainer of networked-aframe, you can now use the original networked-aframe repository. :)

switch back to original networked-aframe

---

src/auth.rs
src/lib.rs

Implements #78. Now if JWT authorization is enabled, you may join a room only if you send a JWT containing `join_hub = true` and with either no `room_ids` (i.e. like all old tokens; you can join any room) or a `room_ids` array containing the room ID you're trying to join.
Not yet tested, so not merging yet.

Add optional room_ids to JWT
